#!/usr/bin/env bash

USER_DB=robomatic
PASS_DB=robomatic
HOST_DB=localhost
PORT_DB=5432

#test-executor
CONN="postgres://$USER_DB:$PASS_DB@$HOST_DB:$PORT_DB/test_executor?sslmode=disable"
echo "DATABASE_URL=\"$CONN\"" > ./test-executor/.env
cat ./test-executor/.env

#core
CONN="postgres://$USER_DB:$PASS_DB@$HOST_DB:$PORT_DB/core?sslmode=disable"
echo "DATABASE_URL=\"$CONN\"" > ./core/.env
cat ./core/.env

#n8n
CONN="postgres://$USER_DB:$PASS_DB@$HOST_DB:$PORT_DB/n8n?sslmode=disable"
echo "DATABASE_URL=\"$CONN\"" > ./n8n/.env
cat ./n8n/.env