#!/usr/bin/env bash

#test-executor
echo "Configurando db para test-executor"
echo "DATABASE_URL=postgres://${USER}:${PASS}@${BD_IP}:${BD_PUERTO}/test_executor?sslmode=disable" > ./payments/.env

#core
echo "Configurando db para core"
echo "DATABASE_URL=postgres://${USER}:${PASS}@${BD_IP}:${BD_PUERTO}/core?sslmode=disable" > ./core/.env